

source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "net-imap", "~> 0.5", ">= 0.5.14"
gem "pony",     "~> 1.13"
gem "puma",     "~> 7.2"
gem "rack",     "~> 3.2", ">= 3.2.6"
gem "sinatra",  "~> 4.2"
gem "google-protobuf", "~> 3.25", ">= 3.25.5"

gem "opentelemetry-sdk", "~> 1.4.1"
gem "opentelemetry-exporter-otlp", "~> 0.26.3"
gem "opentelemetry-instrumentation-all", "~> 0.60.0"
